// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDecision(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateDecision'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateDecisionAfter(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateDecisionAfter'](arg1, arg2, arg3, arg4, arg5);
}

export function CreatePrecursor(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreatePrecursor'](arg1, arg2, arg3, arg4);
}

export function CreateProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3, arg4);
}

export function CreateProximity(arg1, arg2) {
  return window['go']['main']['App']['CreateProximity'](arg1, arg2);
}

export function CreateProximityGroup(arg1) {
  return window['go']['main']['App']['CreateProximityGroup'](arg1);
}

export function CreateTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3);
}

export function CurrentView() {
  return window['go']['main']['App']['CurrentView']();
}

export function DeleteNode(arg1) {
  return window['go']['main']['App']['DeleteNode'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteProximity(arg1) {
  return window['go']['main']['App']['DeleteProximity'](arg1);
}

export function ExportProject(arg1) {
  return window['go']['main']['App']['ExportProject'](arg1);
}

export function GetCompletedMarkdown(arg1) {
  return window['go']['main']['App']['GetCompletedMarkdown'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportProject() {
  return window['go']['main']['App']['ImportProject']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function SaveCompletedMarkdown(arg1) {
  return window['go']['main']['App']['SaveCompletedMarkdown'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetDecisionsCollapsed(arg1, arg2) {
  return window['go']['main']['App']['SetDecisionsCollapsed'](arg1, arg2);
}

export function UpdateNode(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateNode'](arg1, arg2, arg3, arg4);
}

export function UpdateProject(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2, arg3, arg4, arg5);
}
