// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {model} from '../models';
import {config} from '../models';

export function CreateDecision(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<service.ProjectView>;

export function CreateDecisionAfter(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<service.ProjectView>;

export function CreatePrecursor(arg1:string,arg2:string,arg3:string,arg4:string):Promise<service.ProjectView>;

export function CreateProject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<model.Project>;

export function CreateProximity(arg1:string,arg2:string):Promise<service.ProjectView>;

export function CreateProximityGroup(arg1:Array<string>):Promise<service.ProjectView>;

export function CreateTask(arg1:string,arg2:string,arg3:string):Promise<service.ProjectView>;

export function CurrentView():Promise<service.ProjectView>;

export function DeleteNode(arg1:string):Promise<service.ProjectView>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteProximity(arg1:string):Promise<service.ProjectView>;

export function ExportProject(arg1:string):Promise<string>;

export function GetCompletedMarkdown(arg1:string):Promise<string>;

export function GetSettings():Promise<config.Settings>;

export function ImportProject():Promise<model.Project>;

export function ListProjects():Promise<Array<model.Project>>;

export function OpenProject(arg1:string):Promise<service.ProjectView>;

export function SaveCompletedMarkdown(arg1:string):Promise<string>;

export function SaveSettings(arg1:config.Settings):Promise<void>;

export function SetDecisionsCollapsed(arg1:string,arg2:boolean):Promise<service.ProjectView>;

export function UpdateNode(arg1:string,arg2:string,arg3:string,arg4:string):Promise<service.ProjectView>;

export function UpdateProject(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<model.Project>;

export function Version():Promise<string>;
